# Generated by Django 5.2 on 2025-08-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('series_id', models.IntegerField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('image', models.CharField(default='', max_length=255, verbose_name='图片地址')),
                ('rank', models.CharField(default='', max_length=255, verbose_name='排名')),
                ('min_price', models.CharField(default='', max_length=255, verbose_name='最低价格')),
                ('max_price', models.CharField(default='', max_length=255, verbose_name='最高价格')),
                ('brand_name', models.CharField(default='', max_length=255, verbose_name='品牌名称')),
                ('level', models.CharField(default='', max_length=255, verbose_name='等级')),
                ('fuel_forml', models.CharField(default='', max_length=255, verbose_name='能源类型')),
                ('market_time', models.DateField(default='', max_length=255, verbose_name='上市时间')),
            ],
            options={
                'db_table': 'car_data',
            },
        ),
    ]
