# Generated by Django 5.2 on 2025-08-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardata',
            old_name='rank',
            new_name='car_rank',
        ),
    ]
