# Generated by Django 5.2 on 2025-08-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_rename_rank_cardata_car_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='crate_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='market_time',
            field=models.CharField(default='', max_length=255, verbose_name='上市时间'),
        ),
    ]
