# Generated by Django 5.2 on 2025-08-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_cardata_crate_time_alter_cardata_market_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='car_count',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
