# Generated by Django 5.2 on 2025-08-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_cardata_car_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='crate_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
