# Generated by Django 5.2 on 2025-08-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_cardata_crate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='car_rank',
            field=models.IntegerField(default='', max_length=255, verbose_name='排名'),
        ),
    ]
