# Generated by Django 5.2 on 2025-08-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_alter_cardata_car_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='car_rank',
            field=models.IntegerField(default='', verbose_name='排名'),
        ),
    ]
