# Generated by Django 5.2 on 2025-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_alter_cardata_car_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='max_price',
            field=models.FloatField(default=0, verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='min_price',
            field=models.FloatField(default=0, verbose_name='最低价格'),
        ),
    ]
